local you_furry = true
local furry_players = true

local function Decode(str)
	local StringLength = #str
	
	-- Base64 decoding
	do
		local decoder = {}
		for b64code, char in pairs(('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='):split('')) do
			decoder[char:byte()] = b64code-1
		end
		local n = StringLength
		local t,k = table.create(math.floor(n/4)+1),1
		local padding = str:sub(-2) == '==' and 2 or str:sub(-1) == '=' and 1 or 0
		for i = 1, padding > 0 and n-4 or n, 4 do
			local a, b, c, d = str:byte(i,i+3)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40 + decoder[d]
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8),bit32.extract(v,0,8))
			k = k + 1
		end
		if padding == 1 then
			local a, b, c = str:byte(n-3,n-1)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8))
		elseif padding == 2 then
			local a, b = str:byte(n-3,n-2)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000
			t[k] = string.char(bit32.extract(v,16,8))
		end
		str = table.concat(t)
	end
	
	local Position = 1
	local function Parse(fmt)
		local Values = {string.unpack(fmt,str,Position)}
		Position = table.remove(Values)
		return table.unpack(Values)
	end
	
	local Settings = Parse('B')
	local Flags = Parse('B')
	Flags = {
		--[[ValueIndexByteLength]] bit32.extract(Flags,6,2)+1,
		--[[InstanceIndexByteLength]] bit32.extract(Flags,4,2)+1,
		--[[ConnectionsIndexByteLength]] bit32.extract(Flags,2,2)+1,
		--[[MaxPropertiesLengthByteLength]] bit32.extract(Flags,0,2)+1,
		--[[Use Double instead of Float]] bit32.band(Settings,0b1) > 0
	}
	
	local ValueFMT = ('I'..Flags[1])
	local InstanceFMT = ('I'..Flags[2])
	local ConnectionFMT = ('I'..Flags[3])
	local PropertyLengthFMT = ('I'..Flags[4])
	
	local ValuesLength = Parse(ValueFMT)
	local Values = table.create(ValuesLength)
	local CFrameIndexes = {}
	
	local ValueDecoders = {
		--!!Start
		[1] = function(Modifier)
			return Parse('s'..Modifier)
		end,
		--!!Split
		[2] = function(Modifier)
			return Modifier ~= 0
		end,
		--!!Split
		[3] = function()
			return Parse('d')
		end,
		--!!Split
		[4] = function(_,Index)
			table.insert(CFrameIndexes,{Index,Parse(('I'..Flags[1]):rep(3))})
		end,
		--!!Split
		[5] = {CFrame.new,Flags[5] and 'dddddddddddd' or 'ffffffffffff'},
		--!!Split
		[6] = {Color3.fromRGB,'BBB'},
		--!!Split
		[7] = {BrickColor.new,'I2'},
		--!!Split
		[8] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = ColorSequenceKeypoint.new(Parse('f'),Color3.fromRGB(Parse('BBB')))
			end
			return ColorSequence.new(kpts)
		end,
		--!!Split
		[9] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = NumberSequenceKeypoint.new(Parse(Flags[5] and 'ddd' or 'fff'))
			end
			return NumberSequence.new(kpts)
		end,
		--!!Split
		[10] = {Vector3.new,Flags[5] and 'ddd' or 'fff'},
		--!!Split
		[11] = {Vector2.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[12] = {UDim2.new,Flags[5] and 'di2di2' or 'fi2fi2'},
		--!!Split
		[13] = {Rect.new,Flags[5] and 'dddd' or 'ffff'},
		--!!Split
		[14] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Axes.new(unpack(t))
		end,
		--!!Split
		[15] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Faces.new(unpack(t))
		end,
		--!!Split
		[16] = {PhysicalProperties.new,Flags[5] and 'ddddd' or 'fffff'},
		--!!Split
		[17] = {NumberRange.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[18] = {UDim.new,Flags[5] and 'di2' or 'fi2'},
		--!!Split
		[19] = function()
			return Ray.new(Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')),Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')))
		end
		--!!End
	}
	
	for i = 1,ValuesLength do
		local TypeAndModifier = Parse('B')
		local Type = bit32.band(TypeAndModifier,0b11111)
		local Modifier = (TypeAndModifier - Type) / 0b100000
		local Decoder = ValueDecoders[Type]
		if type(Decoder)=='function' then
			Values[i] = Decoder(Modifier,i)
		else
			Values[i] = Decoder[1](Parse(Decoder[2]))
		end
	end
	
	for i,t in pairs(CFrameIndexes) do
		Values[t[1]] = CFrame.fromMatrix(Values[t[2]],Values[t[3]],Values[t[4]])
	end
	
	local InstancesLength = Parse(InstanceFMT)
	local Instances = {}
	local NoParent = {}
	
	for i = 1,InstancesLength do
		local ClassName = Values[Parse(ValueFMT)]
		local obj
		local MeshPartMesh,MeshPartScale
		if ClassName == "UnionOperation" then
			obj = DecodeUnion(Values,Flags,Parse)
			obj.UsePartColor = true
		elseif ClassName:find("Script") then
			obj = Instance.new("Folder")
			Script(obj,ClassName=='ModuleScript')
		elseif ClassName == "MeshPart" then
			obj = Instance.new("Part")
			MeshPartMesh = Instance.new("SpecialMesh")
			MeshPartMesh.MeshType = Enum.MeshType.FileMesh
			MeshPartMesh.Parent = obj
		else
			obj = Instance.new(ClassName)
		end
		local Parent = Instances[Parse(InstanceFMT)]
		local PropertiesLength = Parse(PropertyLengthFMT)
		local AttributesLength = Parse(PropertyLengthFMT)
		Instances[i] = obj
		for i = 1,PropertiesLength do
			local Prop,Value = Values[Parse(ValueFMT)],Values[Parse(ValueFMT)]
			
			-- ok this looks awful
			if MeshPartMesh then
				if Prop == "MeshId" then
					MeshPartMesh.MeshId = Value
					continue
				elseif Prop == "TextureID" then
					MeshPartMesh.TextureId = Value
					continue
				elseif Prop == "Size" then
					if not MeshPartScale then
						MeshPartScale = Value
					else
						MeshPartMesh.Scale = Value / MeshPartScale
					end
				elseif Prop == "MeshSize" then
					if not MeshPartScale then
						MeshPartScale = Value
						MeshPartMesh.Scale = obj.Size / Value
					else
						MeshPartMesh.Scale = MeshPartScale / Value
					end
					continue
				end
			end
			
			obj[Prop] = Value
		end
		if MeshPartMesh then
			if MeshPartMesh.MeshId=='' then
				if MeshPartMesh.TextureId=='' then
					MeshPartMesh.TextureId = 'rbxasset://textures/meshPartFallback.png'
				end
				MeshPartMesh.Scale = obj.Size
			end
		end
		for i = 1,AttributesLength do
			obj:SetAttribute(Values[Parse(ValueFMT)],Values[Parse(ValueFMT)])
		end
		if not Parent then
			table.insert(NoParent,obj)
		else
			obj.Parent = Parent
		end
	end
	
	local ConnectionsLength = Parse(ConnectionFMT)
	for i = 1,ConnectionsLength do
		local a,b,c = Parse(InstanceFMT),Parse(ValueFMT),Parse(InstanceFMT)
		Instances[a][Values[b]] = Instances[c]
	end
	
	return NoParent
end


local Objects = Decode('AFA9AiEGRm9sZGVyIQROYW1lIQ9vd29mdXJyeXNraW51d3UhBU1vZGVsIRBDYXRuaXBBZGRpY3RTYXdsIQpXb3JsZFBpdm90BOYB5wHoASEFUGFudHMhDVBhbnRzVGVtcGxhdGUhK2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MTIzMzkwNDI1OTghBVNoaX'
..'J0IQ1TaGlydFRlbXBsYXRlIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyMzM5MDQxMzMyIQ1DaGFyYWN0ZXJNZXNoIQhCb2R5UGFydAMAAAAAAADwPyEGTWVzaElkAwAAADAO8YZBIQRQYXJ0IQZIYW5kbGUhDUJvdHRvbVN1cmZhY2UDAAAAAAAAAAAh'
..'BkNGcmFtZQQcAOkB6gEhCkNhbkNvbGxpZGUCIQhQb3NpdGlvbgoAQN+8eFvRv0D5zT8hBFNpemUKAACAPwAAgD8AAIA/IQpUb3BTdXJmYWNlIQtTcGVjaWFsTWVzaCEYcmJ4YXNzZXRpZDovLzEyMzMxMDg0MDE2IQlUZXh0dXJlSWQhGHJieGFzc2V0aWQ6Ly8xMjMzMT'
..'k1NzIyMSEITWVzaFR5cGUDAAAAAAAAFEAhC1N0cmluZ1ZhbHVlIQVWYWx1ZSEFVG9yc28hDFBvc2l0aW9uUGFydCF2LTAuMDI3MjUyMTk3MywgLTEuNjM1NjAzOSwgMS42MDkxNjkwMSwgMSwgNy41MjczNTg3MmUtMjMsIC0xLjI1NzMxOTMzZS0yMiwgLTcuNTI3MzU4'
..'NzJlLTIzLCAxLCAwLCAxLjI1NzMxOTMzZS0yMiwgMCwgMQQuAOcB6AEhC09yaWVudGF0aW9uCvypMb8dWqS+zczMPQopuaO7FmbCPhnEEz0hCFJvdGF0aW9uCvypMb8dWqS+ppvEPSEYcmJ4YXNzZXRpZDovLzE1NjkzMjUyOTM0IRhyYnhhc3NldGlkOi8vMTU2Mjk2OD'
..'ExMDQhBEhlYWQhqi0wLjAwNDk5NjQzODA1LCAwLjM3OTY4NTEwNCwgMC4wMzYwNzU2ODUyLCAwLjk5OTk4Mjk1MywgLTAuMDAxNjcyMDYxNjMsIC0wLjAwNTU5Nzg4ODQ5LCAwLjAwMTczOTc4NDAzLCAwLjk5OTkyNTEzNywgMC4wMTIxMTQ4OTA5LCAwLjAwNTU3NzIx'
..'MjY3LCAtMC4wMTIxMjQ0MjI5LCAwLjk5OTkxMTAxBDcA6wHsAQoAAAAAAAA0QwAAAAAK/P+Fu3QL0D4AiIU9CgAANEMAAAAAAAA0QyEYcmJ4YXNzZXRpZDovLzE1ODYzODY2Mzk2IStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTE1Nzg1MTgyMTQ5IZQtMC'
..'4wMDQwODkzNTM2MSwgMC40MDYzMzczOCwgMC4wNjUyMDA4MDU3LCAtMSwgNC4yMDc5NTY0OGUtMTAsIC0yLjk4MDIzMDgyZS0wOCwgNC4yMDc5NTQyNmUtMTAsIDEsIDcuNDUwNTc5NzFlLTA5LCAyLjk4MDIzMDgyZS0wOCwgNy40NTA1Nzk3MWUtMDksIC0xIQltYWtz'
..'dzkxNzIE7QHuAe8BIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyMzM5MDQ5MDk1IStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyMzM5MDUwMjMyBEIA7gHvAQoAAAAAAABiwgAAAAAKmMsFw2DCdT1E3xLDIRhyYnhhc3NldGlkOi8vMT'
..'IzMzE5NjE2MDYhdS0wLjAyNzI1MjE5NzMsIC0xLjYzNTYwMzc5LCAxLjYwOTE2OTAxLCAxLCA3LjUyNzM1NjgzZS0yMywgLTEuMjU3MzE4N2UtMjIsIC03LjUyNzM1NjgzZS0yMywgMSwgMCwgMS4yNTczMTg3ZS0yMiwgMCwgMQRHAPAB7wEKAAAAAAAAoEIAAAAACmIz'
..'tsKMIqo+8LUSwyEYcmJ4YXNzZXRpZDovLzEyMzMxMDgzOTk5IRhyYnhhc3NldGlkOi8vMTIzMzExMDYwNjQhlDAuMDAxMzQ2NTg5NzYsIDAuMzgyNDQwNjg2LCAwLjAyOTgwODA0NDQsIDEsIC03LjYzODU0NDkxZS0wOSwgNi44MzkzNjkwN2UtMTAsIDcuNjM4NTQ0OT'
..'FlLTA5LCAxLCAtOS4zMTMyMjE4NmUtMTAsIC02LjgzOTM2OTA3ZS0xMCwgOS4zMTMyMjE4NmUtMTAsIDEhDnRhY293YWNva2hhem1hBPEB8gHzASEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMjkwMDQwOTUyNyEraHR0cDovL3d3dy5yb2Jsb3guY29t'
..'L2Fzc2V0Lz9pZD0xMjkwMDM5NTY0MSEXWWVsbG93IEtlbW9ubyBGb3ggIFRhaWwEUQDyAfMBCuArZ7/dx7Q/gJSgQSEYcmJ4YXNzZXRpZDovLzEyODg0NzMzNjA3IRhyYnhhc3NldGlkOi8vMTI4OTgxMDkyMjkhkS0wLjAwMzA0OTg0ODYsIC0xLjU4NzY1MDY2LCAxLj'
..'c3MjUyMTk3LCAxLCAtMy4wMjY3OTgzN2UtMDksIDMuNDU2MDg0NzJlLTExLCAzLjAyNjc5ODM3ZS0wOSwgMSwgOS4zMTMyMjEzMWUtMDksIC0zLjQ1NjA4NzVlLTExLCAtOS4zMTMyMjEzMWUtMDksIDEhEVllbGxvdyBLZW1vbm8gRm94BFcA9AH1AQqATma/oEOcQMDe'
..'kkEhGHJieGFzc2V0aWQ6Ly8xMjg5NzA3MzMwMyEYcmJ4YXNzZXRpZDovLzEyODk2MzU3NDI0IZkwLjAwMDMyODA2NTY4MiwgMC4zODMyNTUxMjQsIDAuMDU4Nzc2ODU1NSwgLTEsIC03Ljk4Nzc5MDg3ZS0wOSwgLTEuODE1OTUyMDFlLTEyLCAtNy45ODc3OTA4N2UtMD'
..'ksIDEsIC05LjMxMzIzMDE5ZS0xMCwgMS44MTU5NTk0OWUtMTIsIC05LjMxMzIzMDE5ZS0xMCwgLTEhB1Bhd3RpZXQE9gH3Ae8BIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTE1NjM4MTQ0NTg0IStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lk'
..'PTE1NjM3MzA1NTkwIQtGbHVmZnkgVGFpbARhAPgB+QEKgmamv7Ino8AAAMC/IRdyYnhhc3NldGlkOi8vNjQ1NjE1OTk1MiEYcmJ4YXNzZXRpZDovLzEzMTk5ODM5OTgwIT8wLCAtMS4zNzUxMTQyLCAyLjA1MTA4Nzg2LCAtMSwgMCwgMCwgMCwgMS4wMDAwMDA5NSwgMC'
..'wgMCwgMCwgLTEhFFdoaXRlIExvbmcgQ2F0IFNjYXJmBGcA+gH7AQoI46i/S8eWwD62ZMAhOWh0dHBzOi8vYXNzZXRkZWxpdmVyeS5yb2Jsb3guY29tL3YxL2Fzc2V0Lz9pZD0xMTEwNjQ4Njk4OSEYcmJ4YXNzZXRpZDovLzExMTA2NDg2OTY1IU4tMC4wMTk0MjYzNDU4'
..'LCAtMC45ODgzNDc0NzEsIC0wLjAyMjUzNTMyNDEsIDEsIDAsIDAsIDAsIDEuMDAwMDAzODEsIDAsIDAsIDAsIDEhI0FjY2Vzc29yeSAoTWVzaGVzL0FudGVubmFBY2Nlc3NvcnkpBG0A/AH9AQpmZqa/waE9wMCgjcAhGHJieGFzc2V0aWQ6Ly8xNTIwMTI5NDU2MiEYcm'
..'J4YXNzZXRpZDovLzE1MjAxNjQzMTE2IZ8xLjQxNTI5NTRlLTA2LCAwLjc2MDQ3NTkzNCwgLTAuODc0Nzg0NzA4LCAtMSwgLTEuNDE5ODE4NTdlLTA3LCAtNS4zNjQzOTQ3MmUtMDcsIC0xLjQxOTgyNDY4ZS0wNywgMS4wMDAwMDM4MSwgMS4zNDExMDI2NmUtMDcsIDUu'
..'MzY0Mzk0NzJlLTA3LCAxLjM0MTA5ODI1ZS0wNywgLTEhBEVhcnMEcwD+Af8BCnlmpr+6hVjAhy86wCEYcmJ4YXNzZXRpZDovLzEyMTQwNzYwMjg1IRhyYnhhc3NldGlkOi8vMTMxOTk4MzQ4NDAhnDIuMDQ0MTAyNjZlLTA5LCAwLjM0MDMxMjk1OCwgMC42NDE5MzcyNT'
..'YsIDEsIC03Ljg3MTM3NTU1ZS0wOSwgLTMuMDI5OTgxMjdlLTE1LCA3Ljg3MTQwNTc1ZS0wOSwgMS4wMDAwMDM4MSwgNC4xNDQ0NDE0MmUtMTYsIDMuMDI5OTgxMjdlLTE1LCAtNC4xNDQ0MjU4ZS0xNiwgMSEZTWVzaGVzL2JsdWU1ICgxKUFjY2Vzc29yeQR5AP4B/wEK'
..'AFymvwo9bsCzSmPAIRhyYnhhc3NldGlkOi8vMTM5NTU3ODkwMDYhGHJieGFzc2V0aWQ6Ly8xMzk1NTc4OTAzNiGiMC4wMDAzMTkzNjE2ODcsIDAuMDAxMDAwODg1MDQsIC0wLjAwMDM0NjE4Mzc3NywgMSwgLTcuODcxMzc1NTVlLTA5LCAtMy4wMjk5ODEyN2UtMTUsID'
..'cuODcxNDA1NzVlLTA5LCAxLjAwMDAwMzgxLCA0LjE0NDQ0MTQyZS0xNiwgMy4wMjk5ODEyN2UtMTUsIC00LjE0NDQyNThlLTE2LCAxIQlGYWNlRmx1ZmYEfwD+Af8BCnZmpr9cnXjAx8VwwCEYcmJ4YXNzZXRpZDovLzEyMTIzOTk4Njk1IRhyYnhhc3NldGlkOi8vMTI2'
..'MzQ5MDYwNDchnjUuOTkxMTE2OTRlLTA5LCAtMC4xNjExMjc1ODIsIC0wLjIxMDk4MzI3NiwgMSwgLTcuODcxMzc1NTVlLTA5LCAtMy4wMjk5ODEyN2UtMTUsIDcuODcxNDA1NzVlLTA5LCAxLjAwMDAwMzgxLCA0LjE0NDQ0MTQyZS0xNiwgMy4wMjk5ODEyN2UtMTUsIC'
..'00LjE0NDQyNThlLTE2LCAxBIQAAAL/AQp0Zqa/tPd1wBbggsAhGHJieGFzc2V0aWQ6Ly8xMTQ2MzI5NTk5NCEYcmJ4YXNzZXRpZDovLzExNDYzMzQxNzE0IaI1LjY2MTgzNTA5ZS0wOCwgLTAuMTE5NzY2NTkzLCAtMC41Mzg3NjYzODQsIC0xLCAtNy44NzEzNzU1NWUt'
..'MDksIDMuMDI5OTgxMjdlLTE1LCAtNy44NzE0MDU3NWUtMDksIDEuMDAwMDAzODEsIC00LjE0NDQ0MTQyZS0xNiwgLTMuMDI5OTgxMjdlLTE1LCAtNC4xNDQ0MjU4ZS0xNiwgLTEhGE1lc2hlcy9icm93cyB2N0FjY2Vzc29yeQSKAPgB+wEKdWWov3jgYsCLzoDAIRhyYn'
..'hhc3NldGlkOi8vMTQ0MjQ1OTU0MjkhGHJieGFzc2V0aWQ6Ly8xNDQyNDQwMzI3OSFqLTAuMDE1NTk0NDgyNCwgMC4xNzg1MjUxOCwgLTAuNDc0MTI0NTUxLCAtMSwgLTEuMjU1NzUzMTZlLTMwLCAwLCAtMS4yNTU3NTc5NWUtMzAsIDEuMDAwMDAzODEsIDAsIC0wLCAw'
..'LCAtMSEGZnVycnk0BAECAgIDAiELTWFub2tpdFRhaWwEkgAEAu8BCrAzg8CwCzFAsL3DPyEYcmJ4YXNzZXRpZDovLzExNDQwNjI2NzMyIRhyYnhhc3NldGlkOi8vMTE0NDA2Nzk3NjIhQy02LjEwMzUxNTYyZS0wNSwgLTEuMjMzNjYxNTMsIDIuMTI5MjI2NjgsIDEsID'
..'AsIDAsIDAsIDEsIDAsIDAsIDAsIDEhDUZlYXRoZXJ5IEVhcnMEmAAFAgYCCpg2g8Cs1bJATqlXviEXcmJ4YXNzZXRpZDovLzgyNjE3NDUzOTEhKmh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9ODI2MTY2NjY5NyGVLTAuMDAwNDE1Nzk3OTg2LCAwLjA4ODU4'
..'MzExMTgsIDAuMzg5MzkzNTk4LCAxLCAtNy44NzEzNzU1NWUtMDksIC0zLjAyOTk4MTI3ZS0xNSwgNy44NzEzNzU1NWUtMDksIDEsIDQuMTQ0NDI1NTRlLTE2LCAzLjAyOTk4MTI3ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIDEhHUJlYXV0aWZ1bCBTdHJhaWdodCBCbGFjay'
..'BIYWlyBJ4ABALvAQrFMoPAMyyiQJN21r4hF3JieGFzc2V0aWQ6Ly82NDQwOTcwOTA2IRdyYnhhc3NldGlkOi8vNjQ0MDk3MDk2MCFENS4xMDIxNTc1OWUtMDUsIC0wLjQzMjEwNDQ2OCwgMC4xODExMjY5ODIsIDEsIDAsIDAsIDAsIDEsIDAsIDAsIDAsIDEhGU1lc2hl'
..'cy9tYXNrMiAoMSlBY2Nlc3NvcnkEpgAFAgYCIQZMb2NrZWQiCjAzg8AAALBASHsRvyEXcmJ4YXNzZXRpZDovLzcwNjIwMzYwMDYhF3JieGFzc2V0aWQ6Ly83MDUwMzUxMDE0IZc1LjU2Njg5NTU3ZS0wOCwgNC41MTMzNDQ2NWUtMTYsIDAuMDMxNzEzMDA4OSwgMSwgLT'
..'cuODcxMzc1NTVlLTA5LCAtMy4wMjk5ODEyN2UtMTUsIDcuODcxMzc1NTVlLTA5LCAxLCA0LjE0NDQyNTU0ZS0xNiwgMy4wMjk5ODEyN2UtMTUsIC00LjE0NDQyNThlLTE2LCAxIQdQdW5rUmF0BKwAAgIDAgowM4PArkfBQMiHGb8KhsK1PzEzcz+8HuU/ITFodHRwOi8v'
..'d3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEwMTE5MTIyNiAgICAgICAgIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEwMTE5MTE2MSAgIYktOC4xODYxMDc3OWUtMDksIDAuNTQwMDAwMDgxLCAwLjAwMDI3MjI0NDIxNSwgMSwgLTcuODcxMzc1NTVlLT'
..'A5LCAwLCA3Ljg3MTM3NTU1ZS0wOSwgMSwgNC4xNDQ0MjIxZS0xNiwgLTMuMjYyMjMwMzRlLTI0LCAtNC4xNDQ0MjIxZS0xNiwgMSEqaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD04NzYyMjE0MzE4ISpodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lk'
..'PTQ5Nzk5NDUxMzAhDkNoZXZlbGxlU1MxNjg0BAcCCAIJAiESUGxhbmUuMDYyQWNjZXNzb3J5BLcACAIJAgq20sLAAOCrQBJVi0AhE0NpcmNsZS4wMzJBY2Nlc3NvcnkEugAKAgsCCv68w8C5MO0/Mt+9QCGCLTAuMDI3MjUyMTk3MywgLTEuNjM1NjAzNzksIDEuNjA5MT'
..'Y5MDEsIDEsIDcuNTI3MzU2ODNlLTIzLCAtMS4yNTczMTg3ZS0yMiwgLTcuNTI3MzU2ODNlLTIzLCAxLCAwLCAxLjI1NzMxODdlLTIyLCA5LjgwOTA4OTI1ZS00NSwgMSENSXJvbl9DaGllZjExNwQMAvQB9QEhK2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9'
..'MTMzOTkyMDY1NDMhDFNoaXJ0R3JhcGhpYyEHR3JhcGhpYyEqaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD02NzM1NDI1MjgxIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEzMzk5MjA1NDc1IRFLZW1vbm8gRmVubmVjIEZveATFAPQB9QEKGE'
..'2zwPxkt0F/W1PBIRhyYnhhc3NldGlkOi8vMTI4OTYzNTkyNzkhLUN1dGUgQmxhY2sgQ2lyY2xlIEdsYXNzZXMgKEZpdHMgS2Vtb25vIEhlYWRzKQTJAA0CDgIKjFGzwI+us0HZMFnBIRhyYnhhc3NldGlkOi8vMTI4OTY0NDk0NzYhGHJieGFzc2V0aWQ6Ly8xMjg4Njgy'
..'ODgyNSGcLTAuMDAwMjE1NTA0MDQyLCAtMC4wODA4MTkzNjg0LCAtMC4zMDU4MTA1NzEsIC0xLCAtNy44NzEzNzU1NWUtMDksIC04Ljc0MjI3NzY2ZS0wOCwgLTcuODcxMzc1NTVlLTA5LCAxLCAtMS4xMDI1ODAwM2UtMTUsIDguNzQyMjc3NjZlLTA4LCAtNC4xNDQ0Mj'
..'UyN2UtMTYsIC0xIRZLZW1vbm8gRmVubmVjIEZveCBUYWlsBM8A8gHzAQrEaLPAkqCbQf/vN8EhGHJieGFzc2V0aWQ6Ly8xMjg4NDU0ODAxNiEISnVsaWVuXzcEDwIQAhECIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEzMzk5MjQ1MzgwIStodHRwOi8v'
..'d3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEzMzk5MjQ2MjY0IRBXaGl0ZSBOZWNrIEZsdWZmBNcAEAIRAgrIT7PAZ55MQe68VMEhF3JieGFzc2V0aWQ6Ly84NTMzOTI1MTUwIRdyYnhhc3NldGlkOi8vODUyNjQ0MjQ3NCGXMi4yOTM5OTg3M2UtMDcsIC0wLjc1MjMzOT'
..'YwMiwgLTAuMDI3NTEwMjE0NiwgLTEsIDEuMTg2MzUzNmUtMTgsIC04Ljc0MjI3NzY2ZS0wOCwgMS4xODYzNTM2ZS0xOCwgMSwgLTEuOTMxMzAwNjVlLTIwLCA4Ljc0MjI3NzY2ZS0wOCwgLTEuOTMxMzEwOTllLTIwLCAtMSEGR3JvdXAxBN0AEgIGAgqgELPAr2ZeQS/N'
..'U8EhGHJieGFzc2V0aWQ6Ly8xMzM1NzIzMjAyOCEYcmJ4YXNzZXRpZDovLzEzMzU0NTIzNzcxIZcwLjAwNzcwOTUwNTA0LCAwLjM1OTA1NzA2OSwgMC4wMzEwMjExMTgyLCAtMSwgLTcuODcxMzc1NTVlLTA5LCAzLjAyOTk4MTI3ZS0xNSwgLTcuODcxMzc1NTVlLTA5LC'
..'AxLCAtNC4xNDQ0MjU1NGUtMTYsIC0zLjAyOTk4MTI3ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIC0xIRZEYW5nZXJDb25lSGF0QWNjZXNzb3J5BOMABQIGAgrIU7PAArhnQc8iVMEhGHJieGFzc2V0aWQ6Ly8xMDc1Mjk3NTk5OSEYcmJ4YXNzZXRpZDovLzEwNzUyOTIwODcw'
..'IZUtMC4wMDA0ODgyODM5MjgsIDAuOTQxNDExOTcyLCAwLjAxMDExNjU3NzEsIDEsIC03Ljg3MTM3NTU1ZS0wOSwgLTMuMDI5OTgxMjdlLTE1LCA3Ljg3MTM3NTU1ZS0wOSwgMSwgNC4xNDQ0MjU1NGUtMTYsIDMuMDI5OTgxMjdlLTE1LCAtNC4xNDQ0MjU4ZS0xNiwgMS'
..'EYSGFsbG93ZWVuU25pcGVyQWNjZXNzb3J5BOkABALvAQoY2qfAhjJLQb//SMEhF3JieGFzc2V0aWQ6Ly81Njk5ODE4OTQyIRdyYnhhc3NldGlkOi8vNTY5OTgxOTIzNyE/MC4zNTgxMTYxNSwgMC42NTg4MjI3MTUsIDAuNzA2MTc2NzU4LCAxLCAwLCAwLCAwLCAxLCAw'
..'LCAwLCAwLCAxIRFDdWJlLjAxMkFjY2Vzc29yeQTvABMCFAIKeM2xwPepKkFqrDjBIRhyYnhhc3NldGlkOi8vMTMzNTU4NDM5NzQhGHJieGFzc2V0aWQ6Ly8xMzM1NTUwNjM2MiGFMC4wNDcxNTcyODc2LCAtMS4zNzQ1MTY3MywgMS43MjY1MjE0OSwgLTEsIDAsIC0yLj'
..'A2Nzk1MTUzZS0yNSwgLTEuOTI1OTI5OTRlLTM0LCAxLCA5LjMxMzIyNTc1ZS0xMCwgMi4wNjc5NTE1M2UtMjUsIDkuMzEzMjI1NzVlLTEwLCAtMSEQYWNvbG90aW5ob19wdWRpbQQVAhYCFwIE9gANAg4CCoLfwsAGDf1Ar5eAQCEnTWVzaGVzL0Zsb29mX0N1YmUuMDYw'
..'X0N1YmUuMTA5QWNjZXNzb3J5BPkAFgIXAgq+3cLAylniQOqHikAK3SQWQClc7z+sHNo/IRdyYnhhc3NldGlkOi8vNjEwMjYwNDMzNCEXcmJ4YXNzZXRpZDovLzYxMDI2MTAxNTghYS0yLjY4NzczODc0ZS0wOCwgLTAuOTE1MTk4MDg4LCAwLjAwNDc2NDQ1NjMsIDEsIC'
..'0zLjI5MjI4MzM4ZS0yNSwgMCwgMy4yOTIyODMzOGUtMjUsIDEsIDAsIDAsIDAsIDEhElBsYW5lLjAzNUFjY2Vzc29yeQQAARgCGQIKkuDCwFuYBUGSiYxAIRhyYnhhc3NldGlkOi8vMTIzMzE3MzgzMjEhGHJieGFzc2V0aWQ6Ly8xMjMzMTc0MzUzMCGVLTAuMDAwMzQ1'
..'MjI4MjExLCAwLjM2MTAzNjg5NywgMC4wNjc0NjY3MzU4LCAxLCAtNy44NzEzODI2NmUtMDksIC0zLjAyOTk4NDI0ZS0xNSwgNy44NzEzODI2NmUtMDksIDEsIDQuMTQ0NDI1NTRlLTE2LCAzLjAyOTk4NDI0ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIDEhDldoaXRlIGZveC'
..'B0YWlsBAYBBALvAQraPsPATgGfQKl0vEAhGHJieGFzc2V0aWQ6Ly8xMzUxMzU4NzY3MCEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMzUxMzQ4OTAzNiFALTAuMDExODU0MDc5NiwgLTEuNTE5NzQ5NCwgMS41NjQ5MTQyMywgMSwgMCwgMCwgMCwgMSwg'
..'MCwgMCwgMCwgMSEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMzQ5OTM2MTQxOSEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMDc5ODI4OTk3MiEFZnVycnkEGgIbAhwCIRJQbGFuZS4wMDRBY2Nlc3NvcnkEEQEbAhwCCvypMT8UrjNDg8'
..'DKvQpLg4BCWYlpQ6+4mMIKVk4zQwrXoz6u5zNDIakwLjAxMjg3ODA0MTcsIDAuNDM2NDQ3MjAzLCAwLjAzMzU3MTUyMjcsIC0wLjk5OTk4MzAxMywgLTAuMDAxNjY1MTI5NzksIDAuMDA1NTg5NDQsIC0wLjAwMTczMjc1MDMzLCAwLjk5OTkyNTEzNywgLTAuMDEyMTE0'
..'OTQ2NywgLTAuMDA1NTY4ODQ4NDYsIC0wLjAxMjEyNDQyNTcsIC0wLjk5OTkxMTAxIRhyYnhhc3NldGlkOi8vMTM0Nzc3OTUxNTQhGHJieGFzc2V0aWQ6Ly8xMzQ3Mzc0NjgyMQQXARACEQIKs3yAQgVZaEP115jCIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2'
..'lkPTEyMzQ4NzgzMDc3BBoB9wHvAQqzfIBCCG5mQ9KFlMIhNzAsIC0xLjE3MDI1NDM1LCAyLjEzMjkwNzg3LCAtMSwgMCwgMCwgMCwgMSwgMCwgMCwgMCwgLTEhBVNjYWxlCgAAgD9SuH4/AACAPyEXcmJ4YXNzZXRpZDovLzc0NDkwNjE1NzghKmh0dHA6Ly93d3cucm9i'
..'bG94LmNvbS9hc3NldC8/aWQ9NzQ4NTk4MTc4NCEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xNTM2NjUxNTk1MCEGZnVycnkzBCQBHQIeAiESUGxhbmUuMDMzQWNjZXNzb3J5CgAAAAAAACBAAAAAwSGVLTAuMDAwMzQ1MjI4MzI3LCAwLjM3NDYzOTE1My'
..'wgMC4wMjg0MTE4NjUyLCAxLCAtNy44NzEzODI2NmUtMDksIC0zLjAyOTk4NDI0ZS0xNSwgNy44NzEzODI2NmUtMDksIDEsIDQuMTQ0NDI1NTRlLTE2LCAzLjAyOTk4NDI0ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIDEhGHJieGFzc2V0aWQ6Ly8xMjMzMTczODMxOSEYcmJ4'
..'YXNzZXRpZDovLzEyMzMxNzQ2MTQyIQhSZWRTY2FyZgQkAR8CIAIhXTAuMDI0NzI0OTYwMywgLTEuMDcxMjUwNjgsIDAuMDIwMjEwMjY2MSwgMSwgMCwgLTkuOTIxMTcwNTVlLTEwLCAwLCAxLCAwLCA5LjkyMTE3MDU1ZS0xMCwgMCwgMSEXcmJ4YXNzZXRpZDovLzU4ND'
..'ExMTEwMjYhF3JieGFzc2V0aWQ6Ly81ODQxODQwNjYyIRFXaGl0ZSBLZW1vbm8gVGFpbAQkAfIB8wEhGHJieGFzc2V0aWQ6Ly8xMjg4NDc3MzMzNCEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMjM0ODc4NjM4OCEPbmF2ZWFoX2J1bnRpbjIyBCECIgLv'
..'ASEUQWNjZXNzb3J5IChQdWZmVGFpbCkENgEiAiMCCgAAAAAAALTCAAAAAAogEYM7lKnzv2UoIcAKAACAQAAAgD8AAABAIRhyYnhhc3NldGlkOi8vMTYwOTk4NjkyODEhGHJieGFzc2V0aWQ6Ly8xNjA5OTg3NjI5MCGXLTQuNjk4OTc0MzdlLTA4LCAtMS4yMDAwMDAwNS'
..'wgMS41NzUwMDAwNSwgLTQuMzcxMTM4ODNlLTA4LCAtMS4yMjQ2NDY4NWUtMTYsIC0xLCAxLjIyNDY0Njg1ZS0xNiwgMSwgLTEuMjI0NjQ2ODVlLTE2LCAxLCAtMS4yMjQ2NDY4NWUtMTYsIC00LjM3MTEzODgzZS0wOCEKVHJpZWRUb1BpbgQ+ASQCJQIKBoGKwkqMIsIO'
..'LSpCCszTBL+olw++ZlGSwAoI7JPCi2xVwUjhckAKtM3MP83MTD+6zMw/Cs3MzD7NzMw+zczMPiEYcmJ4YXNzZXRpZDovLzEyOTQwMDYwODQ4IRhyYnhhc3NldGlkOi8vMTI5NDAwNjUxMTEhoi0wLjUyMjg1NjU5MywgMC41NjMzODU1NDYsIC0wLjQ3OTM0NTg1OCwgMC'
..'45NzA4ODcyNDQsIC0wLjA2NDM5NjEyODEsIC0wLjIzMDcxODU1MywgMC4yMzk1MzY4NjcsIDAuMjYxMDA5Mjc2LCAwLjkzNTE0NTAyLCAtMy43MjUyOTAzZS0wOCwgLTAuOTYzMTg1OTY2LCAwLjI2ODgzNTgxMyEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9p'
..'ZD0xNjEwNDU2MTcwNyEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xNjEwNDU1NTk2OQRIASYCIwIKQBGDO2N9sr5K0F/AIRhyYnhhc3NldGlkOi8vMTYwOTk2MDA2NjghGHJieGFzc2V0aWQ6Ly8xNjA5OTYwNDQ2NCGIMCwgMC4zNTQ5OTk2NjEsIDAuNT'
..'k2MDAyNTc5LCAxLjIyNDY0Njg1ZS0xNiwgLTEuMjI0NjQ2ODVlLTE2LCAtMSwgMS4yMjQ2NDY4NWUtMTYsIDEsIC0xLjIyNDY0Njg1ZS0xNiwgMSwgLTEuMjI0NjQ2ODVlLTE2LCAxLjIyNDY0Njg1ZS0xNgRNASYCIwIKABGDO37QxL+Z+oLAIRhyYnhhc3NldGlkOi8v'
..'MTYxMDAwMjk0MDMhGHJieGFzc2V0aWQ6Ly8xNjEwMDAzNjkwOSGMMCwgLTAuODM0MDAwMTExLCA1LjAwOTE5OTgzZS0zMywgMS4yMjQ2NDY4NWUtMTYsIC0xLjIyNDY0Njg1ZS0xNiwgLTEsIDEuMjI0NjQ2ODVlLTE2LCAxLCAtMS4yMjQ2NDY4NWUtMTYsIDEsIC0xLj'
..'IyNDY0Njg1ZS0xNiwgMS4yMjQ2NDY4NWUtMTYEUgEnAigCCiAJgzskYTW/mfqCwAowwck/gsBKPy2CTD8Kum57PzXvez+8bns/IRhyYnhhc3NldGlkOi8vMTYwOTc5NjU5NTMhGHJieGFzc2V0aWQ6Ly8xNjA5Nzk4NzgyNyGfLTkuMzQ3ODk2ODJlLTA3LCAtMC4wMDQ5'
..'MDA5ODQ5MywgLTEuNDExNDk5MDllLTEzLCAtMS41MDk5NTgwM2UtMDcsIC0xLjIyNDY0Njk4ZS0xNiwgLTEsIC0xLjIyNDY0NjcyZS0xNiwgMSwgLTEuMjI0NjQ2ODVlLTE2LCAxLCAxLjIyNDY0NjU5ZS0xNiwgLTEuNTA5OTU4MDNlLTA3BFkBKQIqAgqwnvs8XKg2v7'
..'evhMAhF3JieGFzc2V0aWQ6Ly84Nzg5MDc0MDEwIRdyYnhhc3NldGlkOi8vODc4OTA3NDAzNyGVMC4wMjY3MTU0ODcyLCAtMC4wMDk4OTM4OTQyLCAtMC4wNTMzNTkwNTc4LCAxLCAtNy44NzEzNzU1NWUtMDksIC0zLjAyOTk4MTI3ZS0xNSwgNy44NzEzNzU1NWUtMDks'
..'IDEsIDQuMTQ0NDI1NTRlLTE2LCAzLjAyOTk4MTI3ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIDEEXgEiAiMCCgARgztWUqu+MpSIwAoAAIBAi2xnP65HAUAKAACAP4tsZz+uR4E/IRhyYnhhc3NldGlkOi8vMTYwOTk0MzUwMTQhGHJieGFzc2V0aWQ6Ly8xNjA5OTQzOTA3OC'
..'GYNy42NDk0OTI1OWUtMDksIDAuMzY4OTk5OTg4LCAtMC4xNzQ5OTk5OTcsIC00LjM3MTEzODgzZS0wOCwgLTEuMjI0NjQ2ODVlLTE2LCAtMSwgMS4yMjQ2NDY4NWUtMTYsIDEsIC0xLjIyNDY0Njg1ZS0xNiwgMSwgLTEuMjI0NjQ2ODVlLTE2LCAtNC4zNzExMzg4M2Ut'
..'MDghCm1hbmxlZ28wMzEEKwIEAu8BIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyOTA5Nzg2ODQ3IStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyOTA5Nzg0Njk3IRBUeXBlLTEyQWNjZXNzb3J5BGsBLAItAgoAAAzCAAC0QgAAAAAKuz'
..'MUwEmMjb9PvD8/CgAAtMIAAFxCAAC0Qgo5tMg+2/mKQAaBhT8hF3JieGFzc2V0aWQ6Ly80OTk4NTQwMDI2IRdyYnhhc3NldGlkOi8vNDk5ODU2NTIyMyF1LTAuMjA0OTk5OTI0LCAwLjAyMjAwMzAwOTksIDAuNjA0OTk5NTQyLCAwLCAtMC41NzM1NzY4NjgsIDAuODE5'
..'MTUxODE5LCAwLCAwLjgxOTE1MTgxOSwgMC41NzM1NzY4NjgsIC0xLjAwMDAwMDEyLCAwLCAwIR1NZXNoZXMvZmFudGFzeV93ZWFwb0FjY2Vzc29yeQRzAS4CLwIKAP+Bv9goFcCQmiY+IRhyYnhhc3NldGlkOi8vMTE2OTQxNzEzMDkhGHJieGFzc2V0aWQ6Ly8xMTY5ND'
..'Q5OTg5NiFdMS4wOTUwNjI4NSwgLTEuMjAyNzcxMTksIDAuMDE4NzMxMzg1NSwgLTEsIDAsIDkuNjg1NzU0NzhlLTA4LCAwLCAxLCAwLCAtOS42ODU3NTQ3OGUtMDgsIDAsIC0xIQ5SZWQgS2Vtb25vIEZveAR5AfQB9QEKow8HwI6dPr88nE8+IRhyYnhhc3NldGlkOi8v'
..'MTI4OTYzNTgzMzIhNE1lc2hlcy9GYXN0SGVsbWV0UmVkdXhQYXJ0MSBVUExPQURfQ3ViZS4wMDRBY2Nlc3NvcnkEfQEEAu8BCsgVB8AG1hW/rJAzvgpWDs0/Di0yP6rxoj8hGHJieGFzc2V0aWQ6Ly8xMjIwMDYyMDE4MiEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2'
..'V0Lz9pZD0xMjMwNzgxOTU0NCFgLTQuNzA0NTkyMzZlLTA1LCAwLjU0MjU0OTcyOSwgLTAuMzE5MzI0MTM2LCAxLCAtMy4yOTIyODMzOGUtMjUsIDAsIDMuMjkyMjgzMzhlLTI1LCAxLCAwLCAwLCAwLCAxIRNSZWQgS2Vtb25vIEZveCBUYWlsBIQB8gHzAQr7RgfAtsot'
..'wIhP9T8hGHJieGFzc2V0aWQ6Ly8xMjg4NDU0NzA1MyEGU2xpbmdNBIgBMAIvAgoigw/A4Hwqvzw7DT4KsNDfP8ljiz9cFYM/IRhyYnhhc3NldGlkOi8vMTMwMTMwOTA4ODQhGHJieGFzc2V0aWQ6Ly8xMzAxMzEzNTQ0OSFhLTAuMTMxNzIxNDUyLCAwLjQ2MTg3ODc3Ny'
..'wgLTAuMDA2MDQ2Mjk1MTcsIC0xLCAwLCAtOC43NDIyNzc2NmUtMDgsIDAsIDEsIDAsIDguNzQyMjc3NjZlLTA4LCAwLCAtMSEGZnVycnkyBJEB8gHzASEITWVzaFBhcnQhGkxpZ2h0IEJsdWUgS2Vtb25vIEZveCBUYWlsCgAAnEIAAG5DAAC2wgroOeI/z1wsQGakQkAh'
..'CE1lc2hTaXplIQlUZXh0dXJlSUQhGHJieGFzc2V0aWQ6Ly8xMjg4NDU0NzQ0NCEbTGlnaHQgQmx1ZSBIYXBweSBLZW1vbm8gRm94BJEBMQIyAgpZrvw/ZEQEQJ+0+j8hGHJieGFzc2V0aWQ6Ly8xMzUxNTE4NDE3NArKZQJA/5sGQM5gAUAhGHJieGFzc2V0aWQ6Ly8xMz'
..'UxMzMwNjE5OSGXLTAuMDAxMjk5NzI4MjksIDAuNDM2NDU4NDA5LCAwLjA0MTc4OTgwNzQsIC0xLCAtMy40MzE0NzUxOWUtMDcsIC0xLjM0MTA5Njg5ZS0wNiwgLTMuNDMxNDc5NzRlLTA3LCAxLCAzLjMzNDExMDk0ZS0wNywgMS4zNDEwOTY3OGUtMDYsIDMuMzM0MTE1'
..'NDllLTA3LCAtMSEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMDU3MDg3OTQ1MyEraHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMDU3MDg3NzgwOSEMUGlua1ZpdmlsbG9uBDMCNALvAQSjATQC7wEKAAAAAACAIcMAAAAACoQ5EEFACTw/Up'
..'+4QQoAADRDAACUwQAANEMhF3JieGFzc2V0aWQ6Ly82NTMxNTY1MjMwISpodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTY1MzE0MTc0OTIhkTAuMDE0MDQxOTAxNiwgMC40NTkyMjQ4MiwgLTAuMzk0MDk0NDY3LCAxLCAtNy44NzEzNzU1NWUtMDksIC0zLjAy'
..'OTk4MTI3ZS0xNSwgNy44NzEzNzU1NWUtMDksIDEsIDQuMTQ0NDI1NTRlLTE2LCAzLjAyOTk4MTI3ZS0xNSwgLTQuMTQ0NDI1OGUtMTYsIDEEqgE1AjYCCgAAAAAAAKnCAAAAAAqU0dvAAMF1PcOc7sMhGHJieGFzc2V0aWQ6Ly8xMjg4NjgyNzY4MwSuATcC7wEKAAAAAA'
..'AAtEIAAAAACsMEWcNERVFBl80VQyEXcmJ4YXNzZXRpZDovLzg0OTY1NzA2NjMhF3JieGFzc2V0aWQ6Ly82NTYxMzA5MDU3IUUwLjAwMDkwMDI2ODU1NSwgMC4yMzkzNzM1NjUsIC0wLjA0MzQ1NzAzMTIsIDEsIDAsIDAsIDAsIDEsIDAsIDAsIDAsIDEEswHwAe8BCuTW'
..'osIwJYU9gqYEwyEYcmJ4YXNzZXRpZDovLzEyMzMxNzM4MzIwIZItMC4wMDAzNDUzNDc0NzgsIDAuMzY2MDQ5NDA5LCAwLjAyMDgxNjgwMywgMSwgLTcuODcxMzc5MWUtMDksIC0zLjAyOTk4Mjc1ZS0xNSwgNy44NzEzNzkxZS0wOSwgMSwgNC4xNDQ0MjU1NGUtMTYsID'
..'MuMDI5OTgyNzVlLTE1LCAtNC4xNDQ0MjU4ZS0xNiwgMQS3AQQC7wEK+Mu3wcUq30Ch1rS8IRdyYnhhc3NldGlkOi8vNjQwMTU3NjcyOCEqaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD02NTAzMzg3MzI5IUMtMC4wMDE5Mzc4NjYyMSwgLTAuNzEzNDc4MDg4'
..'LCAxLjc3MjcxNjY0LCAxLCAwLCAwLCAwLCAxLCAwLCAwLCAwLCAxBLwBBALvAQp0k8BAnoZpQBIDXEIhGHJieGFzc2V0aWQ6Ly8xMjQ3MTE2MjQ4MyEYcmJ4YXNzZXRpZDovLzEyNDcxMTE3NDAxIUMwLjAwMDM0OTA0NDgsIDAuNjQ4ODQxMTQzLCAtMC4wOTI0OTExND'
..'k5LCAxLCAwLCAwLCAwLCAxLCAwLCAwLCAwLCAxBMEBBALvAQoAAGXDo0Y9QdKHOsIhK2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MTA2ODU1NTE0MTMhK2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MTA2ODU1NTQ2NjghDUNheXppbGxhMzIy'
..'MjMEOAI5Au8BIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTE1MDg5OTg0MDAxIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTE1MDg5OTgwODgwBMoBOgLvAQoAAAAAAADMwQAAAAAKDvkBQHa3ykGSgSNAIUQyLjEzNDQwNjI1ZS0wOCwgLT'
..'EuNjYwNTQ0ODcsIDEuNzcwMTkxOTEsIC0xLCAwLCAwLCAwLCAxLCAwLCAwLCAwLCAtMSEYcmJ4YXNzZXRpZDovLzE1MDIwMDM3NTU0IRhyYnhhc3NldGlkOi8vMTUwNjczNzc3OTUEzwE1AjYCCogFJMEAwXU9w5zuwwTSATkC7wEKAAAAAACAC0MAAAAACgrNekGWimNA'
..'TlbhQQoAADRDAAAiQgAANEMK9wh4P6yLez/3CHg/IRhyYnhhc3NldGlkOi8vMTM1MzM2MzU2MzchGHJieGFzc2V0aWQ6Ly8xMzUxNDk0MDMxNiELQ05fY2hpcGljYXQEOwI8Au8BIStodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyMzM5MDY0NjEwIStodH'
..'RwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEyMzM5MDYzNjkxBN0BPALvAQoAAAAAAAAsQgAAAAAKGl8dwhRZhj9iRRLDIRhyYnhhc3NldGlkOi8vMTIzMzEwODQwMDYhGHJieGFzc2V0aWQ6Ly8xMjMzMTEwNjE2NCGEMC4wMDM1NDc2Njg0NiwgLTEuNzIwODc3'
..'ODksIDEuNjIwODM0MzUsIDEsIC05LjQyOTg1ODM1ZS0yMywgOS4yNjQ0MjYwMmUtMjMsIDkuNDI5ODU4MzVlLTIzLCAxLCAwLCAtOS4yNjQ0MjYwMmUtMjMsIDguNDA3NzkwNzllLTQ1LCAxBOIBPQLvAQqbj9jB4E+OvoRYE8MhGHJieGFzc2V0aWQ6Ly8xMjMzMTA4ND'
..'AxNCEYcmJ4YXNzZXRpZDovLzEyMzMxMTA2NTUyIaotMC4wMDA5ODY0MzU4LCAwLjM4NzUwMDg4MiwgMC4wMzUzNDc5Nzk1LCAwLjk5OTk4MzEzMiwgLTAuMDAxNjcyMjEwOTksIC0wLjAwNTU3NzgyNTQ4LCAwLjAwMTczOTY5MTI0LCAwLjk5OTkyNTA3NywgMC4wMTIx'
..'MTUxNDQyLCAwLjAwNTU1NzE0ODcyLCAtMC4wMTIxMjQ2NDM3LCAwLjk5OTkxMTEyOQrszX+8zWAdv96tUz8K4v5/P3cJ5DoNwbY7ChQp27oY+38/hKVGvAoAAIA/GAC2miYAGBsKGAC2GgAAgD8AAAAACgAAgL+xVecv+P//Mgq5VecvAACAP/7//zEK5ZvgwtjaSD4jwx'
..'LDCr5LDT8AAAAAi3lVPwoAAAAAAACAPwAAAAAK19AxPgAAAABcHHy/CjC9Zr+YdUlAoLmZQQoAAIA/AABQMRYAGK4KAABQsQAAgD/7/x+yCgAAgL+tOgmy1pL/KwqtOgmyAACAPwQAgLAKhJ+nv1n8gMC/oD3ACgAAgL8AAAAAAAAAAAoAAIC/rXMYNNf/D7UK4nMYNCgA'
..'gD/8/w+0CgAAgD+tcxi01/8PNQqycxg0AACAP8//D7QKAACAvwbgl6sAAAAACgbgl6sAAIA/uP+PqwoAAIA//v8PtNf/DzUKAwAQNAAAgD/P/w+0CgAAgL/+/w801/8PtQowM4PAXICMQNzUiD4KAACAP606BzIhZ3yYCq06B7IAAIA/4OjupQoAAIA/AAAAAAAAAAAKAA'
..'CAP606BzJKVVonCq06B7IAAIA/7ujupQraR8PALixnQCKapEAKAACAP606AzLI/zuwCq06A7IAAIA/+f9/MAoAAIA/FQC2miEAGBsKFQC2GgAAgD8AAAAACu5as8DHgqlBbJBIwQoAAIC/rToHsi69uzMKrToHsgAAgD/s6O6lCvCWrcD8MElBrLRGwQoAAIC/LBOvIS69'
..'uzMKLBOvIQAAgD88aLaeCgAAgL+tOgeySlVapwoAAIC/AACAhwAAgBYKAAAAAAAAgD8AAIAwCr7dwsACGdVAf9ydQAoAAIA/UMjLFgAAAAAKUMjLlgAAgD8AAAAACgAAgD+1OgcyWFVaJwq1OgeyAACAP+7o7qUK8nyAQrH6Z0ONspbCCuP+f790HeO643q2uwp8QNq6GP'
..'t/P4elRrwKAACAPwAAACgAAGAdCgAAAKgAAIA/AAAAAAoAAIA/IIAmEARbiDAKIIAmEAAAgD8AAAAACgjce77I9T+/ZShZwAoAAAAAAAAAAAAAgD8KjBbPmAAAgD8AAAAAChGMeD8nSXU+/iKrswok4oO9AqOFPluTdr8KLr07MwAAAAAAAIA/Cjtk5rMxMY2lAACAPwq8'
..'dBiZAACAPzExjSUKAACAP606BzItvTuzCq06B7IAAIA/EDpwJAp0IBDAZpSPv5xkTT8KAAAAAAAAAAABAIC/Cu/VEr/vs1E/AAAAAAoAAIC/UMjLFgAA0LMKUMjLFgAAgD8AAAAACgAAgL9QyMsWLr27MwoAAIC/5jm4tLz/szUK1jm4tAAAgD+8/7I0Cqro38IFO9JAmL'
..'AjwwpXxXK/AAAAAL91oj4KyErEPfCNMSJJ0n4/Cg+Q5yMAAIA/AAAAAAouvTuzAAAAAAAAgL8KqMQsQFYyS0GJr2DDCvipQr8AAAAAOkImvwrjD2c/AAAAAP9r3D4KkEIEwjiKxT6vzRLDCv85Oz8AAAAAcpcuvwrU0DE+AAAAAFscfL9EAQEAAAABAAIAAwAEAAEAAgAC'
..'AAUABgAHAAgAAgACAAIACAAJAAoACwACAAIAAgALAAwADQAOAAIAAgAPABAAEQASABMAAgAHAAIAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AFgAgAAYABAACACAAEQAhACIAIwAkACUAJgAGAAIAAgATACcAKAAmAAYAAgACACkAJwAqABMAAgAJAAIAFAAVABYAFwArAB'
..'kAGgAsAC0AGwAuAC8AMAAdAB4AHwAWACAACgAEAAIAIAARADEAIgAyACQAJQAmAAoAAgACABMAJwAzACYACgACAAIAKQAnADQAEwACAAkAAgAUABUAFgAXADUAGQAaACwANgAbADcALwA4AB0AHgAfABYAIAAOAAQAAgAgABEAOQAiADoAJAAlACYADgACAAIAKQAnADsA'
..'JgAOAAIAAgATACcAMwAEAAEAAgACADwABgA9AAsAEgACAAIACwAMAD4ACAASAAIAAgAIAAkAPwATABIACQACABQAFQAWABcAQAAZABoALABBABsAQgAvAEEAHQAeAB8AFgAgABUABAACACAAEQAhACIAQwAkACUAJgAVAAIAAgATACcAKAAmABUAAgACACkAJwBEABMAEg'
..'AJAAIAFAAVABYAFwBFABkAGgAsAEYAGwBHAC8ARgAdAB4AHwAWACAAGQAEAAIAIAARAEgAIgBJACQAJQAmABkAAgACACkAJwBKACYAGQACAAIAEwAnADMABAABAAIAAgBLAAYATAALAB0AAgACAAsADABNAAgAHQACAAIACAAJAE4ADgAdAAIADwAQABEAEgATAB0ABwAC'
..'AE8AFQAWABcAUAAZABoAGwBRAB0AHgAfABYAIAAhAAQAAgAgABEAUgAiAFMAJAAlACYAIQACAAIAEwAnACgAJgAhAAIAAgApACcAVAATAB0ACQACAFUAFQAWABcAVgAZABoALAA2ABsAVwAvADgAHQAeAB8AFgAmACUAAgACABMAJwAzACAAJQAEAAIAIAARAFgAIgBZAC'
..'QAJQAmACUAAgACACkAJwBaAAQAAQACAAIAWwAGAFwACAApAAIAAgAIAAkAXQALACkAAgACAAsADABeAA4AKQACAA8AEAARABIAEwApAAkAAgBfABUAFgAXAGAAGQAaACwANgAbAGEALwA4AB0AHgAfABYAIAAtAAQAAgAgABEAYgAiAGMAJAAlACYALQACAAIAEwAnACgA'
..'JgAtAAIAAgApACcAZAATACkABwACAGUAFQAWABcAZgAZABoAGwBnAB0AHgAfABYAIAAxAAQAAgAgABEAaAAiAGkAJAAlACYAMQACAAIAKQAnAGoAJgAxAAIAAgATACcAMwATACkACQACAGsAFQAWABcAbAAZABoALAA2ABsAbQAvADgAHQAeAB8AFgAgADUABAACACAAEQ'
..'BuACIAbwAkACUAJgA1AAIAAgApACcAcAAmADUAAgACABMAJwAzABMAKQAHAAIAcQAVABYAFwByABkAGgAbAHMAHQAeAB8AFgAgADkABAACACAAEQB0ACIAdQAkACUAJgA5AAIAAgApACcAdgAmADkAAgACABMAJwAzABMAKQAHAAIAdwAVABYAFwB4ABkAGgAbAHkAHQAe'
..'AB8AFgAgAD0ABAACACAAEQB6ACIAewAkACUAJgA9AAIAAgApACcAfAAmAD0AAgACABMAJwAzABMAKQAHAAIAfQAVABYAFwB+ABkAGgAbAH8AHQAeAB8AFgAgAEEABAACACAAEQCAACIAgQAkACUAJgBBAAIAAgATACcAMwAmAEEAAgACACkAJwCCABMAKQAJAAIAFAAVAB'
..'YAFwCDABkAGgAsADYAGwCEAC8AOAAdAB4AHwAWACAARQAEAAIAIAARAIUAIgCGACQAJQAmAEUAAgACACkAJwCHACYARQACAAIAEwAnADMAEwApAAkAAgCIABUAFgAXAIkAGQAaACwANgAbAIoALwA4AB0AHgAfABYAIABJAAQAAgAgABEAiwAiAIwAJAAlACYASQACAAIA'
..'KQAnAI0AJgBJAAIAAgATACcAMwAEAAEAAgACAI4ABgCPAA4ATQACAA8AEAARABIAEwBNAAcAAgCQABUAFgAXAJEAGQAaABsAkgAdAB4AHwAWACAATwAEAAIAIAARAJMAIgCUACQAJQAmAE8AAgACACkAJwCVACYATwACAAIAEwAnACgAEwBNAAcAAgCWABUAFgAXAJcAGQ'
..'AaABsAmAAdAB4AHwAWACAAUwAEAAIAIAARAJkAIgCaACQAJQAmAFMAAgACACkAJwCbACYAUwACAAIAEwAnADMAEwBNAAcAAgCcABUAFgAXAJ0AGQAaABsAngAdAB4AHwAWACAAVwAEAAIAIAARAJ8AIgCgACQAJQAmAFcAAgACABMAJwAzACYAVwACAAIAKQAnAKEAEwBN'
..'AAgAAgCiABUAFgAXAKMAGQAaAKQApQAbAKYAHQAeAB8AFgAgAFsABAACACAAEQCnACIAqAAkACUAJgBbAAIAAgApACcAqQAmAFsAAgACABMAJwAzABMATQAHAAIAqgAVABYAFwCrABkAGgAbAKwAHQCtAB8AFgAgAF8AAwARAK4AIgCvACQAJQAmAF8AAgACACkAJwCwAC'
..'YAXwACAAIAEwAnADMACABNAAEACQCxAAsATQACAAIACwAMALIABAABAAIAAgCzAAYAtAATAGUABwACALUAFQAWABcAtgAZABoAGwC3AB0AHgAfABYAIABmAAQAAgAgABEASAAiAEkAJAAlACYAZgACAAIAKQAnAEoAJgBmAAIAAgATACcAMwATAGUABwACALgAFQAWABcA'
..'uQAZABoAGwC6AB0AHgAfABYAIABqAAQAAgAgABEAIQAiAEMAJAAlACYAagACAAIAKQAnALsAJgBqAAIAAgATACcAKAALAGUAAgACAAsADAA+AAgAZQACAAIACAAJAD8ABAABAAIAAgC8AAYAvQAIAHAAAgACAAgACQC+AL8AcAABAMAAwQALAHAAAgACAAsADADCABMAcA'
..'AJAAIAwwAVABYAFwDEABkAGgAsADYAGwDFAC8AOAAdAB4AHwAWACAAdAAEAAIAIAARAFgAIgDGACQAJQAmAHQAAgACABMAJwAzACYAdAACAAIAKQAnAFoAEwBwAAkAAgDHABUAFgAXAMgAGQAaACwANgAbAMkALwA4AB0AHgAfABYAIAB4AAQAAgAgABEAygAiAMsAJAAl'
..'ACYAeAACAAIAEwAnADMAJgB4AAIAAgApACcAzAATAHAABwACAM0AFQAWABcAzgAZABoAGwDPAB0AHgAfABYAIAB8AAQAAgAgABEAUgAiANAAJAAlACYAfAACAAIAEwAnACgAJgB8AAIAAgApACcAVAAEAAEAAgACANEABgDSAAsAgAACAAIACwAMANMACACAAAIAAgAIAA'
..'kA1AATAIAACQACANUAFQAWABcA1gAZABoALAA2ABsA1wAvADgAHQAeAB8AFgAgAIMABAACACAAEQDYACIA2QAkACUAJgCDAAIAAgATACcAMwAmAIMAAgACACkAJwDaABMAgAAJAAIA2wAVABYAFwDcABkAGgAsADYAGwDdAC8AOAAdAB4AHwAWACAAhwAEAAIAIAARAN4A'
..'IgDfACQAJQAmAIcAAgACACkAJwDgACYAhwACAAIAEwAnADMAEwCAAAcAAgDhABUAFgAXAOIAGQAaABsA4wAdAB4AHwAWACAAiwAEAAIAIAARAOQAIgDlACQAJQAmAIsAAgACACkAJwDmACYAiwACAAIAEwAnADMAEwCAAAcAAgDnABUAFgAXAOgAGQAaABsA6QAdAB4AHw'
..'AWACAAjwAEAAIAIAARAOoAIgDrACQAJQAmAI8AAgACACkAJwDsACYAjwACAAIAEwAnACgAEwCAAAkAAgDtABUAFgAXAO4AGQAaACwANgAbAO8ALwA4AB0AHgAfABYAIACTAAQAAgAgABEA8AAiAPEAJAAlACYAkwACAAIAKQAnAPIAJgCTAAIAAgATACcAKAAEAAEAAgAC'
..'APMABgD0ABMAlwAJAAIAxwAVABYAFwD1ABkAGgAsADYAGwD2AC8AOAAdAB4AHwAWACAAmAAEAAIAIAARAMoAIgDLACQAJQAmAJgAAgACABMAJwAzACYAmAACAAIAKQAnAMwAEwCXAAcAAgD3ABUAFgAXAPgAGQAaABsA+QAdAPoAHwAWACAAnAAEAAIAIAARAPsAIgD8AC'
..'QAJQAmAJwAAgACACkAJwD9ACYAnAACAAIAEwAnADMAEwCXAAcAAgD+ABUAFgAXAP8AGQAaABsAAAEdAB4AHwAWACAAoAAEAAIAIAARAAEBIgACASQAJQAmAKAAAgACACkAJwADASYAoAACAAIAEwAnADMAEwCXAAcAAgAEARUAFgAXAAUBGQAaABsABgEdAB4AHwAWACAA'
..'pAAEAAIAIAARAAcBIgAIASQAJQAmAKQAAgACABMAJwAoACYApAACAAIAKQAnAAkBCACXAAIAAgAIAAkACgELAJcAAgACAAsADAALAQQAAQACAAIADAEGAA0BEwCqAAkAAgAOARUAFgAXAA8BGQAaACwAEAEbABEBLwASAR0AHgAfABYAJgCrAAIAAgATACcAMwAmAKsAAg'
..'ACACkAJwATASAAqwAEAAIAIAARABQBIgAVASQAJQATAKoACQACANUAFQAWABcAFgEZABoALAA2ABsAFwEvADgAHQAeAB8AFgAmAK8AAgACABMAJwAzACYArwACAAIAKQAnANoAIACvAAQAAgAgABEA2AAiANkAJAAlAAsAqgACAAIACwAMABgBEwCqAAkAAgAUABUAFgAX'
..'ABkBGQAaACwANgAbABoBLwA4AB0AHgAfABYAJgC0AAIAAgATACcAKAAmALQAAgACACkAJwAbASAAtAAFAAIAIAAcAR0BEQAeASIAHwEkACUACACqAAIAAgAIAAkAIAEOAKoAAgAPABAAEQASAAQAAQACAAIAIQEGACIBEwC6AAcAAgAjARUAFgAXACIBGQAaABsAJAEdAB'
..'4AHwAWACYAuwACAAIAKQAnACUBJgC7AAIAAgATACcAMwAgALsABAACACAAEQAmASIAJwEkACUAEwC6AAcAAgAoARUAFgAXACkBGQAaABsAJAEdAB4AHwAWACYAvwACAAIAKQAnACoBJgC/AAIAAgATACcAMwAgAL8ABAACACAAEQArASIALAEkACUAEwC6AAcAAgAtARUA'
..'FgAXAC4BGQAaABsAJAEdAB4AHwAWACYAwwACAAIAKQAnAFQAJgDDAAIAAgATACcAKAAgAMMABAACACAAEQBSACIALwEkACUACwC6AAEADAAYAQgAugABAAkAMAEEAAEAAgACADEBBgAyARMAyQAJAAIAMwEVABYAFwA0ARkAGgAsADUBGwA2AS8ANQEdADcBHwAWACAAyg'
..'ADABEAOAEiADkBJAAlACYAygACAAIAEwAnACgAJgDKAAIAAgApACcAOgETAMkACQACADsBFQAWABcAPAEZABoALAA9ARsAPgEvAD8BHQBAAR8AFgAgAM4ABAAcAUEBEQBCASIAQwEkACUAJgDOAAIAAgApACcARAEmAM4AAgACABMAJwAoAAgAyQACAAIACAAJAEUBCwDJ'
..'AAIAAgALAAwARgETAMkACQACABQAFQAWABcARwEZABoALAA1ARsASAEvADUBHQA3AR8AFgAgANQAAwARAEkBIgBKASQAJQAmANQAAgACABMAJwAzACYA1AACAAIAKQAnAEsBEwDJAAkAAgAUABUAFgAXAEwBGQAaACwANQEbAE0BLwA1AR0ANwEfABYAIADYAAMAEQBOAS'
..'IATwEkACUAJgDYAAIAAgATACcAMwAmANgAAgACACkAJwBQARMAyQAJAAIAFAAVABYAFwBRARkAGgAsADUBGwBSAS8ANQEdAFMBHwAWACAA3AAEABwBVAERAFUBIgBWASQAJQAmANwAAgACABMAJwAzACYA3AACAAIAKQAnAFcBEwDJAAcAAgAUABUAFgAXAFgBGQAaABsA'
..'WQEdAB4AHwAWACAA4AAEAAIAIAARAFoBIgBbASQAJQAmAOAAAgACABMAJwAzACYA4AACAAIAKQAnAFwBEwDJAAkAAgAUABUAFgAXAF0BGQAaACwANQEbAF4BLwA1AR0AXwEfABYAIADkAAQAHAFgAREAYQEiAGIBJAAlACYA5AACAAIAEwAnADMAJgDkAAIAAgApACcAYw'
..'EEAAEAAgACAGQBBgBlAQgA6AACAAIACAAJAGYBCwDoAAIAAgALAAwAZwETAOgACQACAGgBFQAWABcAaQEZABoALABqARsAawEvAGwBHQBtAR8AFgAgAOsABAACACAAEQBuASIAbwEkACUAJgDrAAIAAgApACcAcAEmAOsAAgACABMAJwAoABMA6AAJAAIAcQEVABYAFwBy'
..'ARkAGgAsADYAGwBzAS8AOAAdAB4AHwAWACAA7wAEAAIAIAARAHQBIgB1ASQAJQAmAO8AAgACACkAJwB2ASYA7wACAAIAEwAnACgAEwDoAAkAAgB3ARUAFgAXAHgBGQAaACwANgAbAHkBLwA4AB0AHgAfABYAIADzAAQAAgAgABEAWAAiAHoBJAAlACYA8wACAAIAKQAnAF'
..'oAJgDzAAIAAgATACcAMwATAOgABwACAHsBFQAWABcAfAEZABoAGwB9AR0AfgEfABYAIAD3AAQAAgAgABEAfwEiAIABJAAlACYA9wACAAIAEwAnADMAJgD3AAIAAgApACcAgQETAOgABwACAIIBFQAWABcAgwEZABoAGwCEAR0AHgAfABYAIAD7AAQAAgAgABEAUgAiAIUB'
..'JAAlACYA+wACAAIAKQAnAFQAJgD7AAIAAgATACcAKAATAOgACQACAIYBFQAWABcAhwEZABoALAA2ABsAiAEvADgAHQCJAR8AFgAgAP8AAwARAIoBIgCLASQAJQAmAP8AAgACABMAJwAoACYA/wACAAIAKQAnAIwBBAABAAIAAgCNAQYAjgGPAQMBCAACAJABFwCOARkAGg'
..'AbAJEBHQCSAREAUgCTAZIBlAGVASYABAECAAIAKQAnAFQAJgAEAQIAAgATACcAKACPAQMBCgACAJYBFwCXARkAGgAsADYAGwCRAS8AOAAdAJgBEQCZAZMBmgGUAZsBJgAHAQIAAgApACcAnAEmAAcBAgACABMAJwAzAAgAAwECAAIACAAJAJ0BCwADAQIAAgALAAwAngEE'
..'AAEAAgACAJ8BBgCgARMADAEJAAIAFAAVABYAFwChARkAGgAsAKIBGwCjAS8ApAEdAB4AHwAWACAADQEEAAIAIAARAKUBIgCmASQAJQAmAA0BAgACABMAJwAzACYADQECAAIAKQAnAKcBEwAMAQkAAgAUABUAFgAXAKgBGQAaACwAqQEbAKoBLwCpAR0AHgAfABYAIAARAQ'
..'QAAgAgABEAygAiAKsBJAAlACYAEQECAAIAEwAnADMAJgARAQIAAgApACcAzAATAAwBCQACABQAFQAWABcArAEZABoALACtARsArgEvAK0BHQAeAB8AFgAgABUBBAACACAAEQCvASIAsAEkACUAJgAVAQIAAgApACcAsQEmABUBAgACABMAJwAzABMADAEJAAIAFAAVABYA'
..'FwCyARkAGgAsAEYAGwCzAS8ARgAdAB4AHwAWACAAGQEEAAIAIAARALQBIgACASQAJQAmABkBAgACACkAJwC1ASYAGQECAAIAEwAnADMAEwAMAQcAAgAUABUAFgAXALYBGQAaABsAtwEdAB4AHwAWACAAHQEEAAIAIAARALgBIgC5ASQAJQAmAB0BAgACABMAJwAoACYAHQ'
..'ECAAIAKQAnALoBEwAMAQcAAgAUABUAFgAXALsBGQAaABsAvAEdAB4AHwAWACAAIQEEAAIAIAARAL0BIgC+ASQAJQAmACEBAgACACkAJwC/ASYAIQECAAIAEwAnACgAEwAMAQcAAgAUABUAFgAXAMABGQAaABsAwQEdAB4AHwAWACAAJQEFAAIAIAAcAR0BEQAeASIAHwEk'
..'ACUAJgAlAQIAAgATACcAKAAmACUBAgACACkAJwAbAQsADAECAAIACwAMAMIBCAAMAQIAAgAIAAkAwwEEAAEAAgACAMQBBgDFAQgAKwECAAIACAAJAMYBCwArAQIAAgALAAwAxwETACsBCQACABQAFQAWABcAyAEZABoALADJARsAygEvAMkBHQAeAB8AFgAmAC4BAgACAB'
..'MAJwAoACYALgECAAIAKQAnAMsBIAAuAQQAAgAgABEAzAEiAM0BJAAlABMAKwEJAAIAFAAVABYAFwDOARkAGgAsAKkBGwDPAS8AqQEdAB4AHwAWACAAMgEEAAIAIAARAMoAIgDLACQAJQAmADIBAgACACkAJwDMACYAMgECAAIAEwAnADMAEwArAQkAAgAUABUAFgAXANAB'
..'GQAaACwA0QEbANIBLwDTAR0A1AEfABYAIAA2AQUAAgAgABwB1AERANUBIgDWASQAJQAmADYBAgACACkAJwCcASYANgECAAIAEwAnADMABAABAAIAAgDXAQYA2AEIADoBAgACAAgACQDZAQsAOgECAAIACwAMANoBEwA6AQkAAgAUABUAFgAXANsBGQAaACwA3AEbAN0BLw'
..'DcAR0AHgAfABYAIAA9AQQAAgAgABEA3gEiAN8BJAAlACYAPQECAAIAKQAnAOABJgA9AQIAAgATACcAKAATADoBCQACABQAFQAWABcA4QEZABoALABGABsA4gEvAEYAHQAeAB8AFgAgAEEBBAACACAAEQDjASIA5AEkACUAJgBBAQIAAgATACcAMwAmAEEBAgACACkAJwDl'
..'AQA=')
for _,obj in pairs(Objects) do
	obj.Parent = game.ReplicatedStorage
end


local function applyFurrySkin(plr)
	task.wait(1)
	local furrySkins = game.ReplicatedStorage.owofurryskinuwu:GetChildren()
	local selectedSkin = furrySkins[math.random(#furrySkins)]:Clone()

	local character = plr.Parent
	if character:FindFirstChild("Head") then
		character.Head.Transparency = 1
		for _, v in pairs(character.Head:GetChildren()) do
			if v:IsA("Decal") or v:IsA("SpecialMesh") then
				v:Destroy()
			end
		end
	end
	for _, v in pairs(character:GetChildren()) do
		if v:IsA("CharacterAppearance") or v:IsA("Accessory") or v:IsA("Hat") then
			v:Destroy()
		end
	end

	for _, item in pairs(selectedSkin:GetChildren()) do
		if item:IsA("CharacterAppearance") then
			item:Clone().Parent = character
		elseif item:IsA("BasePart") then
			local cframeComponents = {}
			for value in item.PositionPart.Value:gmatch("([^,]+)") do
				table.insert(cframeComponents, tonumber(value))
			end
			assert(#cframeComponents == 12, "Invalid number of components for CFrame")

			local weld = Instance.new("Weld")
			weld.C0 = CFrame.new(unpack(cframeComponents))
			if item.Part.Value == "Torso" then
				weld.Part0 = character:FindFirstChild("Torso") or character.UpperTorso
			else
				weld.Part0 = character.Head
			end
			local clonedPart = item:Clone()
			weld.Part1 = clonedPart
			weld.Parent = weld.Part0
			clonedPart.Parent = character
		end
	end
end

local function shouldChangeSkin(plr)
	local player = game.Players:GetPlayerFromCharacter(plr.Parent)
	if player then
		if player == game.Players.LocalPlayer then
			return you_furry
		else
			return furry_players
		end
	else
		return true
	end
end

workspace.DescendantAdded:Connect(function(child)
	if child:IsA("Humanoid") and child.Parent:FindFirstChild("Head") then
		if shouldChangeSkin(child) then
			spawn(function()
				applyFurrySkin(child)
			end)
		end
	end
end)

for _, plr in pairs(workspace:GetDescendants()) do
	if plr:IsA("Humanoid") and plr.Parent:FindFirstChild("Head") then
		if shouldChangeSkin(plr) then
			spawn(function()
				applyFurrySkin(plr)
			end)
		end
	end
end